# Generated by Django 2.2.10 on 2020-05-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20191204_0703'),
        ('tasks', '0002_auto_20200508_1339'),
    ]

    operations = [
    ]
